### ISSUE TITLE
Gibbet game session log: case-sensitivity and reveal all, not one

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [levant9/tasks#10]
Gibbet game session log shows two issues:

1. K and k should be same thing for the hangman. Specifying just one should reveal both large and small letters.
2. Giving a letter should show all cases of it. Klawiatura -> a -> should reveal all 'a's, revealed only one.

```
[tammo@lafk-T470 gibbet-game]$ java -jar target/gibbet-game-1.1-SNAPSHOT.jar                   [INSERT]
Try to guess the word
l
Bad guess, gibbet is raising...
actual word: ___

  _____
a
Bad guess, gibbet is raising...
actual word: ___

  _____
  |/   |    
j
Bad guess, gibbet is raising...
actual word: ___

  _____
  |/   |    
  |    |    
e
Bad guess, gibbet is raising...
actual word: ___

  _____
  |/   |    
  |    |    
  |    |    
o
You guessed some letters, actual word:
_o_
g
Bad guess, gibbet is raising...
actual word: _o_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
s
Bad guess, gibbet is raising...
actual word: _o_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
t
Bad guess, gibbet is raising...
actual word: _o_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
  |   / \   
m
Bad guess, gibbet is raising...
actual word: _o_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
  |   / \   
 /|\        
f
Bad guess, gibbet is raising...
actual word: _o_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
  |   / \   
 /|\        
==========
Word was: Kon
Exception in thread "main" pl.lvt.gibbet_game.GameOverException: Failed to guess the word
	at pl.lvt.gibbet_game.App.checkGameOverExitCondition(App.java:39)
	at pl.lvt.gibbet_game.App.main(App.java:26)
[tammo@lafk-T470 gibbet-game]$ java -jar target/gibbet-game-1.1-SNAPSHOT.jar                   [INSERT]
Try to guess the word
k
Bad guess, gibbet is raising...
actual word: __________

  _____
K
You guessed some letters, actual word:
K_________
O
Bad guess, gibbet is raising...
actual word: K_________

  _____
  |/   |    
o
Bad guess, gibbet is raising...
actual word: K_________

  _____
  |/   |    
  |    |    
n
Bad guess, gibbet is raising...
actual word: K_________

  _____
  |/   |    
  |    |    
  |    |    
a
You guessed some letters, actual word:
K_a_______
e
Bad guess, gibbet is raising...
actual word: K_a_______

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
o
Bad guess, gibbet is raising...
actual word: K_a_______

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
i
You guessed some letters, actual word:
K_a_i_____
u
You guessed some letters, actual word:
K_a_i__u__
r
You guessed some letters, actual word:
K_a_i__ur_
s
Bad guess, gibbet is raising...
actual word: K_a_i__ur_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
  |   / \   
z
Bad guess, gibbet is raising...
actual word: K_a_i__ur_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
  |   / \   
 /|\        
m
Bad guess, gibbet is raising...
actual word: K_a_i__ur_

  _____
  |/   |    
  |    |    
  |    |    
  |    0    
  |   /|\   
  |   / \   
 /|\        
==========
Word was: Klawiatura
Exception in thread "main" pl.lvt.gibbet_game.GameOverException: Failed to guess the word
	at pl.lvt.gibbet_game.App.checkGameOverExitCondition(App.java:39)
	at pl.lvt.gibbet_game.App.main(App.java:26)
[tammo@lafk-T470 gibbet-game]$   
```

**Comment by levant9** [comment]
Fixed.
